param(
    [Parameter(Mandatory = $false)]
    [string]$DllPath
)

$ErrorActionPreference = 'Stop'

function Test-IsAdministrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-RegistryViews {
    if ([Environment]::Is64BitOperatingSystem) {
        return @(
            [Microsoft.Win32.RegistryView]::Registry64,
            [Microsoft.Win32.RegistryView]::Registry32
        )
    }
    return @([Microsoft.Win32.RegistryView]::Registry32)
}

function Remove-HkcuSubKey([string]$SubKey) {
    foreach ($view in Get-RegistryViews) {
        $baseKey = [Microsoft.Win32.RegistryKey]::OpenBaseKey(
            [Microsoft.Win32.RegistryHive]::CurrentUser,
            $view
        )
        try {
            $baseKey.DeleteSubKeyTree($SubKey, $false)
        }
        finally {
            $baseKey.Dispose()
        }
    }
}

if ([string]::IsNullOrWhiteSpace($DllPath)) {
    $packagedDll = Join-Path $PSScriptRoot 'WordGeminiFormula.AddIn.dll'
    $sourceDll = Join-Path $PSScriptRoot '..\src\WordGeminiFormula.AddIn\bin\Release\net48\WordGeminiFormula.AddIn.dll'
    if (Test-Path $packagedDll) { $DllPath = $packagedDll }
    elseif (Test-Path $sourceDll) { $DllPath = $sourceDll }
}

if (-not [string]::IsNullOrWhiteSpace($DllPath)) {
    $DllPath = [System.IO.Path]::GetFullPath($DllPath)
}

if (-not (Test-IsAdministrator)) {
    Write-Host 'Administrator permission is required to remove the COM registration. Opening UAC...' -ForegroundColor Yellow
    $quotedScript = '"' + $PSCommandPath.Replace('"', '\"') + '"'
    $argLine = "-NoProfile -ExecutionPolicy Bypass -File $quotedScript"
    if (-not [string]::IsNullOrWhiteSpace($DllPath)) {
        $quotedDll = '"' + $DllPath.Replace('"', '\"') + '"'
        $argLine += " -DllPath $quotedDll"
    }
    $process = Start-Process -FilePath "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -Verb RunAs -ArgumentList $argLine -Wait -PassThru
    if ($process.ExitCode -ne 0) {
        throw "Elevated uninstaller failed with exit code $($process.ExitCode)."
    }
    exit 0
}

$clsid = '{7BA1B881-3DA4-4FBA-A25D-5F92141658EE}'
$progId = 'WordGeminiFormula.AddIn'
$officeAddinSubKey = "Software\Microsoft\Office\Word\Addins\$progId"

# Remove the machine-wide COM registration generated by RegAsm when the DLL
# is still available. Run both framework bitnesses on 64-bit Windows.
if (-not [string]::IsNullOrWhiteSpace($DllPath) -and (Test-Path $DllPath)) {
    $regasmPaths = New-Object System.Collections.Generic.List[string]
    if ([Environment]::Is64BitOperatingSystem) {
        $regasm64 = "$env:SystemRoot\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe"
        if (Test-Path $regasm64) { $regasmPaths.Add($regasm64) }
    }
    $regasm32 = "$env:SystemRoot\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe"
    if (Test-Path $regasm32) { $regasmPaths.Add($regasm32) }

    foreach ($regasm in $regasmPaths) {
        & $regasm $DllPath /nologo /unregister | Out-Null
    }
}

# Remove Word discovery keys and any legacy V0.1 per-user COM keys.
Remove-HkcuSubKey $officeAddinSubKey
Remove-HkcuSubKey "Software\Classes\CLSID\$clsid"
Remove-HkcuSubKey "Software\Classes\$progId"

Write-Host 'Word Gemini Formula registration was removed. Close and reopen Word.' -ForegroundColor Green
